# from reacher_int_dreamer_rn.yaml
training:
  training_stage: -1
  seed: 1887299
  lr: 0.000004 # 0.00004
  num_epochs : 1000000000
  t : 0.02
  batch_size : 5000
  keep_top : 5

  # from_ckpt: '/scorpio/home/yubei-stu-2/mosim/ckpt/atari_boxing/atari_boxing_save-slr_10180733/best_img.pth'
  comment: 'save-slr-tvar'
#   task_name: 'atari_pong'
#   save_path : 'ckpt/atari_pong'
# data:
#   train_data_path : '/scorpio/home/yubei-stu-2/mosim/data/trans-Pong-v5-random.npz'
#   test_data_path : '/scorpio/home/yubei-stu-2/mosim/data/trans-Pong-v5-random-test.npz'
  task_name: 'atari_boxing'
  act_mode: 'random'
  save_path : 'ckpt/atari_boxing'
data:
  train_data_path : '/scorpio/home/yubei-stu-2/mosim/data/trans-Boxing-v5-random.npz'
  test_data_path : '/scorpio/home/yubei-stu-2/mosim/data/trans-Boxing-v5-random-test.npz'
model:
  ## model_param:
  q_dim: 128
  v_dim : 0
  action_dim : 1

  real_t : 0.02
  activation : 'softplus' #['softplus','atan','relu']
  dynamic_model_type:  'resnet_direct'  #['rigid_body','resnet']
  ### Residual Module:
  dynamics_hidden_block_num : 7
  dynamics_network_width : 64
  ### correctors:
  crt_num : 0
  crt_hidden_block_num : 3
  crt_network_width : 64
