# from reacher_int_dreamer_rn.yaml
training:
  training_stage: -1
  seed: 1887299
  lr: 0.0004 # llr0.0004 # ori0.00004
  num_epochs : 1000000000
  t : 0.02
  batch_size : 5000
  keep_top : 5

  comment: 'save-llr'
  task: 'Point3D'
  save_path : 'ckpt/Point3D'
data:
  train_data_path : 'data/trans-Point3D-random.npz'
  test_data_path : 'data/trans-Point3D-random-test.npz'
model:
  ## model_param:
  q_dim: 12
  v_dim : 0
  action_dim : 1

  real_t : 0.02
  activation : 'softplus' #['softplus','atan','relu']
  dynamic_model_type:  'resnet_direct'  #['rigid_body','resnet']
  ### Residual Module:
  dynamics_hidden_block_num : 7
  dynamics_network_width : 64
  ### correctors:
  crt_num : 0
  crt_hidden_block_num : 3
  crt_network_width : 64
